In [1]:
import pandas as pd
import pickle

In [2]:
df= pd.read_csv('Crop_recommendation.csv')
df

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [3]:
df.head(10)

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice
5  69  37  42    23.058049  83.370118  7.073454  251.055000  rice
6  69  55  38    22.708838  82.639414  5.700806  271.324860  rice
7  94  53  40    20.277744  82.894086  5.718627  241.974195  rice
8  89  54  38    24.515881  83.535216  6.685346  230.446236  rice
9  68  58  38    23.223974  83.033227  6.336254  221.209196  rice

In [4]:
df.tail()

        N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [6]:
df.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [7]:
df[['temperature']]

      temperature
0       20.879744
1       21.770462
2       23.004459
3       26.491096
4       20.130175
...           ...
2195    26.774637
2196    27.417112
2197    24.131797
2198    26.272418
2199    23.603016

[2200 rows x 1 columns]

In [8]:
df.shape

(2200, 8)

In [9]:
cleandf=df.dropna()
cleandf

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [10]:
cleandf.shape

(2200, 8)

In [11]:
x=cleandf[['N','P','K','temperature','humidity','ph','rainfall']].values
x

array([[ 90.        ,  42.        ,  43.        , ...,  82.00274423,
          6.50298529, 202.9355362 ],
       [ 85.        ,  58.        ,  41.        , ...,  80.31964408,
          7.03809636, 226.6555374 ],
       [ 60.        ,  55.        ,  44.        , ...,  82.3207629 ,
          7.84020714, 263.9642476 ],
       ...,
       [118.        ,  33.        ,  30.        , ...,  67.22512329,
          6.36260785, 173.3228386 ],
       [117.        ,  32.        ,  34.        , ...,  52.12739421,
          6.75879255, 127.1752928 ],
       [104.        ,  18.        ,  30.        , ...,  60.39647474,
          6.77983261, 140.9370415 ]])

In [12]:
x.shape

(2200, 7)

In [13]:
y=cleandf[['label']].values
y

array([['rice'],
       ['rice'],
       ['rice'],
       ...,
       ['coffee'],
       ['coffee'],
       ['coffee']], dtype=object)

In [14]:
cleandf.dtypes

N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label           object
dtype: object

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100)
x_train,x_test,y_train,y_test

(array([[131.        ,  60.        ,  17.        , ...,  81.79475917,
           7.42504132,  83.46532547],
        [  9.        ,  66.        ,  21.        , ...,  34.13307843,
           5.71988988, 157.0858232 ],
        [ 38.        ,  15.        ,  27.        , ...,  48.50387598,
           6.77778813,  92.26439205],
        ...,
        [ 81.        ,  41.        ,  38.        , ...,  83.72874389,
           7.52408008, 200.9133156 ],
        [ 37.        ,  10.        ,  32.        , ...,  95.16333673,
           6.16508485, 222.803013  ],
        [  2.        , 123.        , 205.        , ...,  90.78572467,
           5.73965218, 124.9831618 ]]),
 array([[ 59.        ,  62.        ,  52.        , ...,  93.10887229,
           6.60866768, 103.8235658 ],
        [ 52.        ,  51.        ,  53.        , ...,  93.10378595,
           6.98580408, 210.2735346 ],
        [ 18.        ,  21.        ,  35.        , ...,  94.94330457,
           6.36856052, 111.1382096 ],
        ...,
        [ 88.        ,  35.        ,  40.        , ...,  83.58760316,
           5.85393208, 291.2986618 ],
        [ 17.        ,  16.        ,  14.        , ...,  92.18151927,
           6.62553865, 102.944161  ],
        [104.        ,  17.        ,  46.        , ...,  80.22972777,
           6.19001591,  43.08961827]]),
 array([['cotton'],
        ['pigeonpeas'],
        ['mango'],
        ...,
        ['rice'],
        ['coconut'],
        ['apple']], dtype=object),
 array([['papaya'],
        ['papaya'],
        ['pomegranate'],
        ['cotton'],
        ['jute'],
        ['maize'],
        ['muskmelon'],
        ['rice'],
        ['mungbean'],
        ['kidneybeans'],
        ['banana'],
        ['pomegranate'],
        ['papaya'],
        ['mango'],
        ['coffee'],
        ['mothbeans'],
        ['pigeonpeas'],
        ['cotton'],
        ['papaya'],
        ['mothbeans'],
        ['coconut'],
        ['cotton'],
        ['mango'],
        ['mango'],
        ['mungbean'],
        ['cotton'],
        ['apple'],
        ['papaya'],
        ['blackgram'],
        ['mothbeans'],
        ['cotton'],
        ['coffee'],
        ['pigeonpeas'],
        ['mango'],
        ['banana'],
        ['muskmelon'],
        ['cotton'],
        ['papaya'],
        ['watermelon'],
        ['kidneybeans'],
        ['jute'],
        ['blackgram'],
        ['maize'],
        ['papaya'],
        ['apple'],
        ['blackgram'],
        ['maize'],
        ['cotton'],
        ['mothbeans'],
        ['pigeonpeas'],
        ['grapes'],
        ['kidneybeans'],
        ['mothbeans'],
        ['kidneybeans'],
        ['mothbeans'],
        ['orange'],
        ['jute'],
        ['orange'],
        ['kidneybeans'],
        ['banana'],
        ['maize'],
        ['blackgram'],
        ['maize'],
        ['grapes'],
        ['lentil'],
        ['pomegranate'],
        ['kidneybeans'],
        ['grapes'],
        ['orange'],
        ['kidneybeans'],
        ['pomegranate'],
        ['grapes'],
        ['jute'],
        ['watermelon'],
        ['blackgram'],
        ['kidneybeans'],
        ['jute'],
        ['coffee'],
        ['mungbean'],
        ['grapes'],
        ['cotton'],
        ['apple'],
        ['kidneybeans'],
        ['apple'],
        ['muskmelon'],
        ['pomegranate'],
        ['papaya'],
        ['coffee'],
        ['blackgram'],
        ['cotton'],
        ['orange'],
        ['jute'],
        ['cotton'],
        ['pomegranate'],
        ['mango'],
        ['apple'],
        ['maize'],
        ['cotton'],
        ['mango'],
        ['grapes'],
        ['pomegranate'],
        ['cotton'],
        ['coffee'],
        ['apple'],
        ['blackgram'],
        ['maize'],
        ['pomegranate'],
        ['mothbeans'],
        ['banana'],
        ['kidneybeans'],
        ['lentil'],
        ['apple'],
        ['coconut'],
        ['coconut'],
        ['mango'],
        ['lentil'],
        ['chickpea'],
        ['mothbeans'],
        ['mungbean'],
        ['maize'],
        ['mango'],
        ['coconut'],
        ['blackgram'],
        ['coffee'],
        ['orange'],
        ['jute'],
        ['chickpea'],
        ['mungbean'],
        ['lentil'],
        ['watermelon'],
        ['coconut'],
        ['apple'],
        ['papaya'],
        ['rice'],
        ['banana'],
        ['grapes'],
        ['grapes'],
        ['papaya'],
        ['papaya'],
        ['rice'],
        ['banana'],
        ['kidneybeans'],
        ['coffee'],
        ['muskmelon'],
        ['maize'],
        ['rice'],
        ['pomegranate'],
        ['pomegranate'],
        ['grapes'],
        ['apple'],
        ['muskmelon'],
        ['muskmelon'],
        ['papaya'],
        ['coconut'],
        ['chickpea'],
        ['banana'],
        ['jute'],
        ['watermelon'],
        ['orange'],
        ['papaya'],
        ['papaya'],
        ['chickpea'],
        ['banana'],
        ['coffee'],
        ['pomegranate'],
        ['chickpea'],
        ['lentil'],
        ['jute'],
        ['lentil'],
        ['pigeonpeas'],
        ['coconut'],
        ['kidneybeans'],
        ['rice'],
        ['chickpea'],
        ['cotton'],
        ['banana'],
        ['mothbeans'],
        ['mango'],
        ['mungbean'],
        ['coconut'],
        ['grapes'],
        ['lentil'],
        ['pigeonpeas'],
        ['coffee'],
        ['lentil'],
        ['cotton'],
        ['lentil'],
        ['jute'],
        ['chickpea'],
        ['rice'],
        ['muskmelon'],
        ['apple'],
        ['mothbeans'],
        ['banana'],
        ['coffee'],
        ['chickpea'],
        ['kidneybeans'],
        ['chickpea'],
        ['orange'],
        ['kidneybeans'],
        ['kidneybeans'],
        ['maize'],
        ['orange'],
        ['cotton'],
        ['cotton'],
        ['chickpea'],
        ['grapes'],
        ['banana'],
        ['muskmelon'],
        ['muskmelon'],
        ['banana'],
        ['jute'],
        ['rice'],
        ['blackgram'],
        ['mothbeans'],
        ['pomegranate'],
        ['coffee'],
        ['rice'],
        ['orange'],
        ['orange'],
        ['mothbeans'],
        ['mango'],
        ['coconut'],
        ['chickpea'],
        ['mango'],
        ['maize'],
        ['pomegranate'],
        ['orange'],
        ['mango'],
        ['mango'],
        ['mungbean'],
        ['coconut'],
        ['pomegranate'],
        ['chickpea'],
        ['pomegranate'],
        ['papaya'],
        ['rice'],
        ['jute'],
        ['mothbeans'],
        ['mungbean'],
        ['jute'],
        ['banana'],
        ['mango'],
        ['orange'],
        ['mungbean'],
        ['kidneybeans'],
        ['mango'],
        ['coffee'],
        ['jute'],
        ['pigeonpeas'],
        ['muskmelon'],
        ['pomegranate'],
        ['chickpea'],
        ['grapes'],
        ['coconut'],
        ['banana'],
        ['pigeonpeas'],
        ['apple'],
        ['cotton'],
        ['chickpea'],
        ['chickpea'],
        ['cotton'],
        ['chickpea'],
        ['lentil'],
        ['blackgram'],
        ['mothbeans'],
        ['jute'],
        ['mungbean'],
        ['coconut'],
        ['mothbeans'],
        ['pomegranate'],
        ['pigeonpeas'],
        ['pigeonpeas'],
        ['jute'],
        ['apple'],
        ['coconut'],
        ['apple'],
        ['chickpea'],
        ['pigeonpeas'],
        ['coffee'],
        ['orange'],
        ['blackgram'],
        ['lentil'],
        ['chickpea'],
        ['coconut'],
        ['pomegranate'],
        ['mothbeans'],
        ['papaya'],
        ['grapes'],
        ['maize'],
        ['banana'],
        ['pigeonpeas'],
        ['muskmelon'],
        ['rice'],
        ['kidneybeans'],
        ['grapes'],
        ['cotton'],
        ['mango'],
        ['coconut'],
        ['maize'],
        ['coconut'],
        ['banana'],
        ['jute'],
        ['watermelon'],
        ['watermelon'],
        ['coconut'],
        ['grapes'],
        ['orange'],
        ['mothbeans'],
        ['grapes'],
        ['pigeonpeas'],
        ['banana'],
        ['coconut'],
        ['coffee'],
        ['maize'],
        ['pomegranate'],
        ['coconut'],
        ['coffee'],
        ['papaya'],
        ['coconut'],
        ['chickpea'],
        ['jute'],
        ['mango'],
        ['mango'],
        ['mungbean'],
        ['mungbean'],
        ['lentil'],
        ['blackgram'],
        ['banana'],
        ['maize'],
        ['apple'],
        ['blackgram'],
        ['lentil'],
        ['coffee'],
        ['papaya'],
        ['rice'],
        ['watermelon'],
        ['mothbeans'],
        ['watermelon'],
        ['coffee'],
        ['coffee'],
        ['muskmelon'],
        ['pigeonpeas'],
        ['kidneybeans'],
        ['chickpea'],
        ['rice'],
        ['blackgram'],
        ['banana'],
        ['grapes'],
        ['jute'],
        ['blackgram'],
        ['coffee'],
        ['pomegranate'],
        ['chickpea'],
        ['papaya'],
        ['orange'],
        ['chickpea'],
        ['muskmelon'],
        ['banana'],
        ['jute'],
        ['chickpea'],
        ['maize'],
        ['kidneybeans'],
        ['coffee'],
        ['orange'],
        ['rice'],
        ['lentil'],
        ['blackgram'],
        ['lentil'],
        ['rice'],
        ['cotton'],
        ['apple'],
        ['muskmelon'],
        ['maize'],
        ['lentil'],
        ['blackgram'],
        ['mothbeans'],
        ['lentil'],
        ['blackgram'],
        ['lentil'],
        ['pomegranate'],
        ['coconut'],
        ['mango'],
        ['coconut'],
        ['cotton'],
        ['orange'],
        ['coconut'],
        ['rice'],
        ['papaya'],
        ['lentil'],
        ['maize'],
        ['apple'],
        ['coffee'],
        ['watermelon'],
        ['pigeonpeas'],
        ['lentil'],
        ['mungbean'],
        ['jute'],
        ['jute'],
        ['watermelon'],
        ['grapes'],
        ['coconut'],
        ['pomegranate'],
        ['apple'],
        ['grapes'],
        ['apple'],
        ['muskmelon'],
        ['orange'],
        ['kidneybeans'],
        ['blackgram'],
        ['cotton'],
        ['grapes'],
        ['mango'],
        ['coffee'],
        ['cotton'],
        ['lentil'],
        ['papaya'],
        ['cotton'],
        ['coffee'],
        ['chickpea'],
        ['maize'],
        ['blackgram'],
        ['pomegranate'],
        ['jute'],
        ['orange'],
        ['cotton'],
        ['watermelon'],
        ['blackgram'],
        ['pomegranate'],
        ['blackgram'],
        ['pigeonpeas'],
        ['cotton'],
        ['maize'],
        ['banana'],
        ['rice'],
        ['watermelon'],
        ['chickpea'],
        ['rice'],
        ['orange'],
        ['watermelon']], dtype=object))

In [16]:
x_train.shape,y_train.shape

((1760, 7), (1760, 1))

In [17]:
x_test.shape,y_test.shape

((440, 7), (440, 1))

In [18]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
rf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
rf.fit(x_train,y_train)

C:\Users\gbavi\AppData\Local\Temp\ipykernel_22404\4211396190.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(x_train,y_train)

RandomForestClassifier()

In [19]:
y_pred2=rf.predict(x_test)
y_pred2

array(['papaya', 'papaya', 'pomegranate', 'cotton', 'jute', 'maize',
       'muskmelon', 'rice', 'mungbean', 'kidneybeans', 'banana',
       'pomegranate', 'papaya', 'mango', 'coffee', 'mothbeans',
       'pigeonpeas', 'cotton', 'papaya', 'mothbeans', 'coconut', 'cotton',
       'mango', 'mango', 'mungbean', 'cotton', 'apple', 'papaya',
       'blackgram', 'mothbeans', 'cotton', 'coffee', 'pigeonpeas',
       'mango', 'banana', 'muskmelon', 'cotton', 'papaya', 'watermelon',
       'kidneybeans', 'jute', 'blackgram', 'maize', 'papaya', 'apple',
       'blackgram', 'maize', 'cotton', 'mothbeans', 'pigeonpeas',
       'grapes', 'kidneybeans', 'mothbeans', 'kidneybeans', 'mothbeans',
       'orange', 'jute', 'orange', 'kidneybeans', 'banana', 'maize',
       'blackgram', 'maize', 'grapes', 'lentil', 'pomegranate',
       'kidneybeans', 'grapes', 'orange', 'kidneybeans', 'pomegranate',
       'grapes', 'jute', 'watermelon', 'blackgram', 'kidneybeans', 'jute',
       'coffee', 'mungbean', 'grapes', 'cotton', 'apple', 'kidneybeans',
       'apple', 'muskmelon', 'pomegranate', 'papaya', 'coffee',
       'blackgram', 'cotton', 'orange', 'jute', 'cotton', 'pomegranate',
       'mango', 'apple', 'maize', 'cotton', 'mango', 'grapes',
       'pomegranate', 'cotton', 'coffee', 'apple', 'blackgram', 'maize',
       'pomegranate', 'mothbeans', 'banana', 'kidneybeans', 'lentil',
       'apple', 'coconut', 'coconut', 'mango', 'lentil', 'chickpea',
       'mothbeans', 'mungbean', 'maize', 'mango', 'coconut', 'blackgram',
       'coffee', 'orange', 'jute', 'chickpea', 'mungbean', 'lentil',
       'watermelon', 'coconut', 'apple', 'papaya', 'rice', 'banana',
       'grapes', 'grapes', 'papaya', 'papaya', 'rice', 'banana',
       'kidneybeans', 'coffee', 'muskmelon', 'maize', 'rice',
       'pomegranate', 'pomegranate', 'grapes', 'apple', 'muskmelon',
       'muskmelon', 'papaya', 'coconut', 'chickpea', 'banana', 'jute',
       'watermelon', 'orange', 'papaya', 'papaya', 'chickpea', 'banana',
       'coffee', 'pomegranate', 'chickpea', 'lentil', 'jute', 'lentil',
       'pigeonpeas', 'coconut', 'kidneybeans', 'rice', 'chickpea',
       'cotton', 'banana', 'mothbeans', 'mango', 'mungbean', 'coconut',
       'grapes', 'lentil', 'pigeonpeas', 'coffee', 'lentil', 'cotton',
       'lentil', 'jute', 'chickpea', 'rice', 'muskmelon', 'apple',
       'mothbeans', 'banana', 'coffee', 'chickpea', 'kidneybeans',
       'chickpea', 'orange', 'kidneybeans', 'kidneybeans', 'maize',
       'orange', 'cotton', 'cotton', 'chickpea', 'grapes', 'banana',
       'muskmelon', 'muskmelon', 'banana', 'jute', 'rice', 'blackgram',
       'mothbeans', 'pomegranate', 'coffee', 'rice', 'orange', 'orange',
       'mothbeans', 'mango', 'coconut', 'chickpea', 'mango', 'maize',
       'pomegranate', 'orange', 'mango', 'mango', 'mungbean', 'coconut',
       'pomegranate', 'chickpea', 'pomegranate', 'papaya', 'rice', 'jute',
       'mothbeans', 'mungbean', 'jute', 'banana', 'mango', 'orange',
       'mungbean', 'kidneybeans', 'mango', 'coffee', 'jute', 'pigeonpeas',
       'muskmelon', 'pomegranate', 'chickpea', 'grapes', 'coconut',
       'banana', 'pigeonpeas', 'apple', 'cotton', 'chickpea', 'chickpea',
       'cotton', 'chickpea', 'lentil', 'blackgram', 'mothbeans', 'jute',
       'mungbean', 'coconut', 'mothbeans', 'pomegranate', 'pigeonpeas',
       'pigeonpeas', 'jute', 'apple', 'coconut', 'apple', 'chickpea',
       'pigeonpeas', 'coffee', 'orange', 'blackgram', 'lentil',
       'chickpea', 'coconut', 'pomegranate', 'mothbeans', 'papaya',
       'grapes', 'maize', 'banana', 'pigeonpeas', 'muskmelon', 'rice',
       'kidneybeans', 'grapes', 'cotton', 'mango', 'coconut', 'maize',
       'coconut', 'banana', 'jute', 'watermelon', 'watermelon', 'coconut',
       'grapes', 'orange', 'mothbeans', 'grapes', 'pigeonpeas', 'banana',
       'coconut', 'coffee', 'maize', 'pomegranate', 'coconut', 'coffee',
       'papaya', 'coconut', 'chickpea', 'jute', 'mango', 'mango',
       'mungbean', 'mungbean', 'lentil', 'blackgram', 'banana', 'maize',
       'apple', 'maize', 'lentil', 'coffee', 'papaya', 'rice',
       'watermelon', 'mothbeans', 'watermelon', 'coffee', 'coffee',
       'muskmelon', 'pigeonpeas', 'kidneybeans', 'chickpea', 'rice',
       'blackgram', 'banana', 'grapes', 'jute', 'blackgram', 'coffee',
       'pomegranate', 'chickpea', 'papaya', 'orange', 'chickpea',
       'muskmelon', 'banana', 'jute', 'chickpea', 'maize', 'kidneybeans',
       'coffee', 'orange', 'rice', 'lentil', 'blackgram', 'lentil',
       'rice', 'cotton', 'apple', 'muskmelon', 'maize', 'lentil',
       'blackgram', 'mothbeans', 'lentil', 'blackgram', 'lentil',
       'pomegranate', 'coconut', 'mango', 'coconut', 'cotton', 'orange',
       'coconut', 'rice', 'papaya', 'lentil', 'maize', 'apple', 'coffee',
       'watermelon', 'pigeonpeas', 'lentil', 'mungbean', 'jute', 'jute',
       'watermelon', 'grapes', 'coconut', 'pomegranate', 'apple',
       'grapes', 'apple', 'muskmelon', 'orange', 'kidneybeans',
       'blackgram', 'cotton', 'grapes', 'mango', 'coffee', 'cotton',
       'lentil', 'papaya', 'cotton', 'coffee', 'chickpea', 'maize',
       'blackgram', 'pomegranate', 'jute', 'orange', 'cotton',
       'watermelon', 'blackgram', 'pomegranate', 'blackgram',
       'pigeonpeas', 'cotton', 'maize', 'banana', 'rice', 'watermelon',
       'chickpea', 'rice', 'orange', 'watermelon'], dtype=object)

In [20]:
 from sklearn import metrics
 accuracy = metrics.accuracy_score(y_test, y_pred2)
 accuracy

0.9977272727272727

In [21]:
pickle.dump(rf,open('crop.pkl', 'wb'))